[tool.poetry]
name = "project-data-platform"
version = "0.1.0"
description = ""
authors = ["lynn pepin <lynn@lynndotpy.xyz>"]
readme = "README.md"
packages = [{include = "project_data_platform"}]

[tool.poetry.dependencies]
python = "^3.10"
yamale = "^4.0.4"
sympy = "^1.11.1"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
